name: GitLab Contributions Calendar

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Generate GitLab calendar
        uses: samantha.gomez/gitlab-calendar@v1
        with:
          gitlab-username: samantha.gomez

      - name: Commit changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add gitlab-calendar.svg
          git commit -m "update gitlab calendar" || exit 0
          git push
